-- AlterTable
ALTER TABLE "Membership" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "status" TEXT DEFAULT 'idle',
ADD COLUMN     "total" DOUBLE PRECISION,
ALTER COLUMN "activatedAt" DROP NOT NULL,
ALTER COLUMN "activatedAt" DROP DEFAULT,
ALTER COLUMN "expiresAt" DROP NOT NULL;
